pipelines:
  - name: TestBash
    configuration:
      environmentVariables:
        readOnly:
          pipe: yes
    steps:
      - name: run
        type: Bash
        configuration:
          environmentVariables:
            foo: bar
            fizz: bin
        execution:
          # onStart: do
          onExecute:
            - echo foo is $foo and fizz is $fizz
