pipelines:
  - name: dockerRun
    steps:
      - name: runCommandsInDocker
        type: Bash
        configuration:
          # nodePool: k8s-dynamic-pool
          runtime:
            type: image
            image:
              custom:
                name: golang
                tag: 1.16
                autoPull: true
        execution:
          onExecute:
            - docker ps && docker images
            - echo "Running commands in container!!!"
            - go version
            - echo "Checking helm version"
            - helm version
            - sleep 10
