pipelines:
  - name: dockerRun
    steps:
      - name: runCommandsInDocker
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              custom:
                name: golang
                tag: 1.13.9
                autoPull: true
        execution:
          onExecute:
            - echo "Running commands in container!!!"
            - go version
            - sleep 10
            
  
