pipelines:
  - name: dockerRun
    steps:
      - name: runCommandsInDocker
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              custom:
                name: golang
                tag: 1.16.0
                autoPull: true
        execution:
          onExecute:
            - docker ps && docker images
            - echo "Running commands in container!!!"
            - go version
            - echo "Checking helm version"
      - name: checkHelm
        type: Bash
        execution:
          onExecute:
            - echo "Checking helm version"
            - sleep 10
