pipelines:
  - name: dockerRun
    steps:
      - name: runCommandsInDocker
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              custom:
                name: alpine
                tag: latest
        execution:
          onExecute:
            - echo "I'm running in container!!!"
   
