pipelines:
  - name: dockerRun
    steps:
      - name: runCommandsInDocker
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              custom:
                name: golang
                tag: 1.14.6
                autoPull: true
        execution:
          onExecute:
            - docker ps && docker images
            - echo "Running commands in container!!!"
            - go version
            - echo "Checking helm version"
            - helm version
            - sleep 10
