pipelines:
  - name: dockerRun
    steps:
      - name: runCommandsInDocker
        type: Bash
        configuration:
          # nodePool: k8s-dynamic-nodepool
          runtime:
            type: image
            image:
              custom:
                name: golang
                tag: 1.14.6
                autoPull: true
        execution:
          onExecute:
            - docker ps
            - echo "Running commands in container!!!"
            - go version
            - sleep 10
            
  
