pipelines:
  - name: dockerRun
    steps:
      - name: runCommandsInDocker
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              custom:
                name: docker.jfrog.io/golang
                tag: 1.13-stretch
                autoPull: false
        execution:
          onExecute:
            - go version
  
