pipelines:
  - name: dockerRun
    steps:
      - name: runCommandsInDocker
        type: Bash
        configuration:
          nodePool: k8s_dynamic_pool
          runtime:
            type: image
            image:
              custom:
                name: golang
                tag: 1.13.9
                autoPull: true
        execution:
          onExecute:
            - docker ps
            - echo "Running commands in container!!!"
            - go version
            - sleep 10
            
  
