pipelines:
  - name: helmRun
    configuration:
      environmentVariables:
        readOnly:
          pipe_env_var: 
            description: pipe env var description
            default: pipe_default_value
    steps:
      - name: checkHelm
        type: Bash
        configuration:
          environmentVariables:
            env1: value1
            env2:
              description: step description
              default: value1
              values:
                - value1
                - value2
              allowCustom: false
        execution:
          onExecute:
            - echo ${pipe_env_var}
            - echo ${env2}
            - echo "Checking helm 3 version"
            - helm3 version
            - sleep 10
