pipelines:
  - name: helmRun
    configuration:
      environmentVariables:
        readOnly:
          FORCE: 
            description: Force chart release
            default: no
            values:
              - no
              - yes
            allowCustom: false
          FORCE_CHART:
            description: Set chart name or select all
            default: all
            values:
              - all
            allowCustom: true
          DIVIDER: "------------------------------------"
          HELM_VERSION: 3.5.3
          CHARTS_BRANCH: develop
    steps:
      - name: checkHelm
        type: Bash
        configuration:
          environmentVariables:
            env2:
              description: step description
              default: value1
              values:
                - value1
                - value2
              allowCustom: true
        execution:
          onExecute:
            - echo ${FORCE}
            - echo ${FORCE_CHART}
            - echo ${env2}
            - echo "Checking helm 3 version"
            - helm3 version
            - sleep 10
