pipelines:
  - name: helmRun
    configuration:
      environmentVariables:
        step_env_var:
          description: step description
          default: value0
          values:
            - value1
            - value2
          allowCustom: true
    steps:
      - name: checkHelm
        type: Bash
        execution:
          onExecute:
            - echo ${step_env_var}
            - echo "Checking helm 3 version"
            - helm3 version
            - sleep 10
