pipelines:
  - name: basic_pipeline
    steps:

      - name: step_2
        type: Bash
        execution:
          onExecute:
            - echo "Hello world!"
            - echo $first_stepid

      - name: step_3
        type: Bash
        configuration:
          inputSteps:
            - name: step_2
        execution:
          onExecute:
            - echo "Hello world!"
            - echo $first_stepid
