resources:
  - name: img_1
    type: Image
    configuration:
      registry: rimas_dockerhub
      imageName: busybox
      imageTag: latest
      autoPull: true

pipelines:
      - name: start
        type: bash
        requires:
          resources:
            - img_1
        execution:
          onExecute:
            - echo "Hello, world!"
      - name: top1
        type: bash
        triggeredBy:
          steps:
            - start
        execution:
          onExecute:
            - echo "Hello, world!"
      - name: top2
        type: bash
        triggeredBy:
          steps:
            - top1
        execution:
          onExecute:
            - echo "Hello, world!"
      - name: top3
        type: bash
        requires:
          resources:
            - img_1
        triggeredBy:
          steps:
            - top2
        execution:
          onExecute:
            - echo "Hello, world!"
      - name: bottom1
        type: bash
        triggeredBy:
          steps:
            - start
        execution:
          onExecute:
            - echo "Hello, world!"
      - name: final
        type: bash
        triggeredBy:
          steps:
            - top3
            - bottom1
        execution:
          onExecute:
            - echo "Hello, world!"
